num1=int(input("please enter your number:"))
num2=int(input("please enter your number:"))
num3=int(input("please enter your number:"))
print(num1 + num2 + num3)
print(num1 * num2 * num3)
print(num1 - num2 - num3)
print(num1 / num2 / num3)