num1 = int(input("print number"))
num2 = int(input("print number"))
num3 = int(input("print number"))
print(num1 + num2 + num3)
print(num1 - num2 + num3)
print(num1 / num2 * num3)
print(num1 / num2 + num3) 
print(num1 + num2 - num3)
print(num1 - num2 * num3)
print(num3 - num2 - num1)
print(num2 + num3 * num1)
print(num1 / num3 + num2)
print(num1 - num2 - num3)